### ISSUE TITLE
Taking wandb settings from env vars?

### ISSUE THREAD

**Issue by yaroslavvb** [cloneofsimo/min-max-gpt#8]
What do you think about changing the code to take settings from env vars instead of being hardcoded to project "mup"?

IE, the user would do this
```
export WANDB_API_KEY=...
export WANDB_PROJECT=muP
```
And the change to allow this

<img width="438" alt="Screenshot 2024-03-05 at 5 35 18 PM" src="https://github.com/cloneofsimo/min-max-gpt/assets/23068/4e3ee52a-374e-46ff-ac1f-5c85c7369a56">

**Comment by cloneofsimo** [comment]
Thatd be nice. Let me make that modification

**Comment by cloneofsimo** [comment]
Done.
